
 spring:
   application:
     name: HotelManagementSystem

   datasource:
     url: jdbc:mysql://localhost:3306/hotel_db
     username: root
     password: Salam24@

   jpa:
     hibernate:
       ddl-auto: update

     show-sql: true

     properties:
       hibernate:
         format_sql: true

 server:
   port: 8082

 jwt:
    secret: myJwtSecretKeyForHotelManagementSystemApplication2026SpringBootJava21SecureKey
    expiration: 86400000